### ISSUE TITLE
RFE: Customization of the module URLs

### ISSUE THREAD

**Issue by jamesfalkner** [Crosbie/username-distribution#5]
It would be awesome if I could add a URL argument to the module so that the clickable URL for user1 is something like  `http:<guides-url>?user=user1`.

Perhaps a simple substitution mechanism like `LAB_MODULE_URLS=http://foo?user={{ASSIGNED_USER_ID}}` where the `{{ASSIGNED_USER_ID}}` variable is replaced with one or more variables in the code, like the user's ID. This would let the things that the URL points to consume query parameters e.g. `?user=user1` and use them to further customize their content for specific users.

**Comment by evanshortiss** [comment]
Could be done as part of the suggested solution to #6

**Comment by Crosbie** [comment]
Module URLs are now suffixed with "?user={{username}}"

**Comment by jamesfalkner** [comment]
Hate to ask, but the parameter name I need is `userid`, not `user` :( 

Would you consider using some simple templating mechanism to do simple substitution? So you could establish a list of possible substitutions like

* `USER_ID` == The user id assigned to the user
* `LAB_USER_ACCESS_TOKEN` == Access token required to join the lab.

 Then in my URL list, I could put in tokens like this:

`LAB_MODULE_URLS=http://example1.com?userid={{USER_ID}}&pass={{LAB_USER_ACCESS_TOKEN}};Lab1,http://example2.com?userid={{USER_ID}};Serverless,http://example3.com`

That way you don't have to hard-code `user=` and so forth.
